### PR TITLE
revise: suppress UnusedCall if no outputs and remove OutputSection lint rule

### LINKED ISSUE #528: `OutputSection` lint rule should be deprecated/removed
**Describe the bug**

This was discussed in detail in the Slack channel, but there is no real need for this to be enforced.

**Expected behavior**

We shouldn't have lint rules that don't serve a purpose.

### LINKED ISSUE #530: `UnusedCall` should be suppressed if the call doesn't have an output section
**Describe the bug**
Any call without an output section being called by a workflow should be assumed that it's intentional (and is meant to be some kind of validate task).

**Additional context**

related to #528

### PR DESCRIPTION
**Pull request by a-frantz**
_Describe the problem or feature in addition to a link to the issues._

closes #530 
closes #528 

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [CONTRIBUTING](https://github.com/stjude-rust-labs/wdl/blob/main/CONTRIBUTING.md) guide in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [x] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [x] Your commit messages follow the [conventional commit] style.
- [x] Your PR title follows the [conventional commit] style.

[conventional commit]: https://www.conventionalcommits.org/en/v1.0.0/#summary
["keep a changelog"]: https://keepachangelog.com/en/1.1.0/

### CODE REVIEW

File: wdl-analysis/src/document/v1.rs [hunk 1]
```diff
@@ -1128,6 +1107,7 @@ fn add_call_statement(
     mut scope: ScopeRefMut<'_>,
     statement: &CallStatement,
     nested_inputs_allowed: bool,
+    any_outputs_used: bool,
```
Comment (peterhuene) [inline wdl-analysis/src/document/v1.rs:1110]: Nit: 
```suggestion
    is_used: bool,
```

**Review by peterhuene — COMMENTED** [review]
Just the one nit. Looks good!
