### PR TITLE
fix: move import validation from `wdl-analysis` to `wdl-ast`.

### LINKED ISSUE #152: Validate import strings during AST validation
There are [`expect()` statements](https://github.com/stjude-rust-labs/wdl/pull/133#discussion_r1700652051) in `wdl-format` (#133) that can currently panic as their assumptions are only validated in analysis. Those checks should move to AST validation.

### PR DESCRIPTION
**Pull request by peterhuene**
This commit moves the validation of imports from `wdl-anlaysis` to `wdl-ast` where the rest of the validation visits occur.

Fixes #152.

Before submitting this PR, please make sure:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [x] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [x] Your commit messages follow the [conventional commit] style.

[conventional commit]: https://www.conventionalcommits.org/en/v1.0.0/#summary
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

File: wdl-ast/src/validation/imports.rs [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+
+/// Creates an "empty import" diagnostic
+fn empty_import(span: Span) -> Diagnostic {
+    Diagnostic::error("import URI cannot be empty").with_highlight(span)
+}
+
+/// Creates a "placeholder in import" diagnostic
+fn placeholder_in_import(span: Span) -> Diagnostic {
+    Diagnostic::error("import URI cannot contain placeholders")
+        .with_label("remove this placeholder", span)
```
Comment (a-frantz) [inline wdl-ast/src/validation/imports.rs:23]: should this be:
```suggestion
        .with_fix("remove this placeholder", span)
```
?

**Review by a-frantz — APPROVED** [review]
