### PR TITLE
fix: correct optional type handling in `check_placeholder`

### LINKED ISSUE #342: spec compliance: placeholder options are not enforcing type requirements
In the function [`check_placeholder`](https://github.com/stjude-rust-labs/wdl/blob/3c69f90a09f1bb43439abdfe7fec5463b8f0fb56/wdl-analysis/src/types/v1.rs#L643) in `wdl-analysis`, we're accepting arrays of primitives for the `sep` option, but otherwise not enforcing the requirements from the WDL specification relating to placeholder options.

For the [`sep` option](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#sep), it is only allowed if the type of the expression is `Array[P]` (where `P` is any primitive type).

For the [`default` option](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#default), it is only allowed if the type of the expression is optional.

For the [`true` and `false` option](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#true-and-false), it is only allowed if the type of the expression is `Boolean`.

We should emit diagnostics when the types of the expressions are not the expected one for the option.

Additionally, in `wdl-engine`, we should also be enforcing these requirements and emitting the same diagnostic if the value produced by the expression is of a type that is not supported by the placeholder option.

This is needed as the type calculation for an expression in `wdl-analysis` can be `Union`, which means the type is statically indeterminate. An example of this would be `~{true="yes" false="no" read_json("file")}`. This should emit no diagnostics from `wdl-analysis`, but should emit a diagnostic error from `wdl-engine` if the file does not contain a boolean.

### PR DESCRIPTION
**Pull request by Ankush1oo8**
_Describe the problem or feature in addition to a link to the issues._

Before submitting this PR, please make sure:
- Corrected the optional type check in `check_placeholder` function.
- Ensured proper handling of `Type::Primitive(_, bool)`.
- Passed all tests successfully.

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [x] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [x] Your commit messages follow the [conventional commit] style.

Fixes #342

### CODE REVIEW

**Comment by adthrasher** [comment]
@Ankush1oo8 - Please update your PR description to use the provided template: https://github.com/stjude-rust-labs/wdl/blob/main/.github/pull_request_template.md?plain=1

**Comment by adthrasher** [comment]
@Ankush1oo8 - Also in the future, please comment on issues to declare interest and claim them prior to working on a PR. This allows to us avoid duplication of work.

File: wdl-analysis/src/types/v1.rs [hunk 1]
```diff
@@ -642,40 +642,48 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
+    
                     if !coercible {
                         self.context
                             .add_diagnostic(cannot_coerce_to_string(&ty, expr.span()));
                     }
                 }
             }
         }
-
+
```
Comment (adthrasher) [inline wdl-analysis/src/types/v1.rs:684]: Please remove the extraneous whitespace.

File: wdl-analysis/src/types/v1.rs [hunk 2]
```diff
@@ -642,40 +642,48 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
                             .add_diagnostic(cannot_coerce_to_string(&ty, expr.span()));
                     }
                 }
             }
         }
-
+    
         self.placeholders -= 1;
-    }
+    }
```
Comment (adthrasher) [inline wdl-analysis/src/types/v1.rs:686]: Please remove the extraneous whitespace.

**Comment by Ankush1oo8** [comment]
> @Ankush1oo8 - Also in the future, please comment on issues to declare interest and claim them prior to working on a PR. This allows to us avoid duplication of work.

Okey sir

File: wdl-analysis/tests/analysis/type_checker_tests.rs [hunk 3]
```diff
@@ -0,0 +1,46 @@
+#[cfg(test)]
```
[the remark this answers is not in the document]
Comment (peterhuene) [reply wdl-analysis/tests/analysis/type_checker_tests.rs:1]: Similarly, we would add a test for the `Sep` option as `wdl-engine/tests/tasks/invalid-placeholder-sep/source.wdl` that would probably look like this:

`source.wdl`:

```wdl
# This is a test of an invalid `sep` placeholder option at runtime.
version 1.2

task test {
    command<<<>>>

    output {
        String a = "~{sep="," read_json("not-array.json")}"
    }
}
```

`inputs.json`:

```json
{}
```

`not-array.json`:

```json
true
```

With `error.txt` initially being empty, but will be populated when you run the `wdl-engine` tests with `BLESS=1`.

I would expect `error.txt` to then contain a diagnostic informing me that the `sep` placeholder option cannot be used on a value of type `Boolean`.

And then similar tests for the `Default` and `TrueFalse` options.

**Comment by Ankush1oo8** [comment]
> Hi @Ankush1oo8, thanks very much for the PR!
> 
> Overall, I think this is a great first step towards fixing #342!
> 
> I've added some feedback comments from my review; would you mind looking them over and discussing them with me? Thanks!

Yes understanding and implementimg them

File: wdl-analysis/tests/analysis/type_checker_tests.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Ankush1oo8) [reply wdl-analysis/tests/analysis/type_checker_tests.rs:1]: done

File: wdl-analysis/src/types/v1.rs [hunk 4]
```diff
@@ -642,41 +642,43 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
             match ty {
                 Type::Primitive(..) | Type::Union | Type::None => {
-                    // OK
                 }
                 ty => {
-                    // Check for a sep option is specified; if so, accept `Array[P]` where `P` is
-                    // primitive.
                     let mut coercible = false;
                     if let Some(PlaceholderOption::Sep(_)) = placeholder.option() {
                         if let Type::Compound(CompoundType::Array(ty), _) = &ty {
```
[the remark this answers is not in the document]
Comment (Ankush1oo8) [reply wdl-analysis/src/types/v1.rs]: done

File: wdl-engine/tests/workflows/primitive-literals/error.txt
Comment (peterhuene) [inline wdl-engine/tests/workflows/primitive-literals/error.txt:1]: This file should not have been added; I suspect the task failed for some reason unrelated to the test (like a permissions issue).

I would delete this file and run the tests again; if it still fails, let me know and I can try to help you diagnosis the issue.

File: wdl-engine/tests/tasks/relative-and-absolute-task/error.txt
Comment (peterhuene) [inline wdl-engine/tests/tasks/relative-and-absolute-task/error.txt:1]: This file should not have been added.

I would delete this file and run the tests again; if it still fails, let me know and I can try to help you diagnosis the issue.

File: wdl-engine/tests/tasks/primitive-literals/error.txt
Comment (peterhuene) [inline wdl-engine/tests/tasks/primitive-literals/error.txt:1]: This file should not have been added and is probably the result of a local issue on your system.

I would delete this file and run the tests again; if it still fails, let me know and I can try to help you diagnosis the issue.

**Review by peterhuene — CHANGES_REQUESTED** [review]
Hi @Ankush1oo8. I've reviewed your changes and this is headed in the right direction, but there's a few comments I have. Thanks!

**Comment by Ankush1oo8** [comment]
@peterhuene I will follow the suggestions Thanks

**Comment by Ankush1oo8** [comment]
@peterhuene hey Hi I have created he function as you said 
```
pub(crate) fn check_placeholder(&mut self, placeholder: &Placeholder) {
        self.placeholders += 1;  // Track placeholder processing count
    
        let expr = placeholder.expr(); // Extract expression inside placeholder
    
        // Evaluate the placeholder expression and check that the resulting type is
        // coercible to string for interpolation
        if let Some(ty) = self.evaluate_expr(&expr) {
            match ty {
                // If the type is already coercible, do nothing
                Type::Primitive(..) | Type::Union | Type::None => {
                    // Validate primitive types with their options
                    if let Some(option) = placeholder.option() {
                        let valid = match option {
                            PlaceholderOption::Sep(_) => false, // Sep option is not valid for primitives
                            PlaceholderOption::Default(_) => matches!(ty, Type::Primitive(_, true)),
                            PlaceholderOption::TrueFalse(_) => matches!(ty, Type::Primitive(PrimitiveType::Boolean, _)),
                        };
                        
                        if !valid {
                            self.context.add_diagnostic(
                                Self::invalid_placeholder_option(&ty, expr.span(), Some(option))
                            );
                        }
                    } else {
                        // Apply cannot_coerce_to_string if no option is specified
                        self.context.add_diagnostic(cannot_coerce_to_string(&ty, expr.span()));
                    }
                }
    
                // Otherwise, check placeholder options
                _ => {
                    let coercible = match placeholder.option() {
                        // `Sep` option: Only `Array[P]` where `P` is a non-optional primitive or Union is valid
                        Some(PlaceholderOption::Sep(_)) => matches!(ty, 
                            Type::Compound(CompoundType::Array(ref element_type), false) // Enforcing non-optional Array
                            if matches!(element_type.element_type(), Type::Primitive(_, false) | Type::Union)),
    
                        // `Default` option: Only optional primitive types are valid
                        Some(PlaceholderOption::Default(_)) => matches!(ty, 
                            Type::Primitive(_, true)),
    
                        // `TrueFalse` option: Only Boolean type is valid
                        Some(PlaceholderOption::TrueFalse(_)) => matches!(ty, 
                            Type::Primitive(PrimitiveType::Boolean, _)),
    
                        None => false, // Apply cannot_coerce_to_string if no option is specified
                    };
                    if !coercible {
                        self.context
                            .add_diagnostic(
                                Self::invalid_placeholder_option(&ty, expr.span(), placeholder.option())
                                
                            );
                    }
                }
            }
        }
    
        self.placeholders -= 1;
    }

/// Generates a diagnostic message for invalid placeholder options.
fn invalid_placeholder_option(ty: &Type, span: Span, option: Option<PlaceholderOption>) -> Diagnostic {
    let message = match option {
        Some(PlaceholderOption::Sep(_)) => format!(
            "type mismatch for placeholder option `sep`: expected type `Array[P]` where P: any primitive type or Union, but found `{}`", ty
        ),
        Some(PlaceholderOption::Default(_)) => format!(
            "type mismatch for placeholder option `default`: expected an optional primitive type, but found `{}`", ty
        ),
        Some(PlaceholderOption::TrueFalse(_)) => format!(
            "type mismatch for placeholder option `truefalse`: expected type `Boolean`, but found `{}`", ty
        ),
        None => "Unexpected type for placeholder".to_string(),
    };
    
    return Diagnostic::error(message);
}

    

    /// Evaluates the type of a literal array expression.
    fn evaluate_literal_array(&mut self, expr: &LiteralArray) -> Type {
        // Look at the first array element to determine the element type
        // The remaining elements must have a common type
        let mut elements = expr.elements();
        match elements
            .next()
            .and_then(|e| Some((self.evaluate_expr(&e)?, e.span())))
        {
            Some((mut expected, mut expected_span)) => {
                // Ensure the remaining element types share a common type
                for expr in elements {
                    if let Some(actual) = self.evaluate_expr(&expr) {
                        if let Some(ty) = expected.common_type(&actual) {
                            expected = ty;
                            expected_span = expr.span();
                        } else {
                            self.context.add_diagnostic(no_common_type(
                                &expected,
                                expected_span,
                                &actual,
                                expr.span(),
                            ));
                        }
                    }
                }

                ArrayType::non_empty(expected).into()
            }
            // Treat empty array as `Array[Union]`
            None => ArrayType::new(Type::Union).into(),
        }
    }
 ```
    but i dont know what to do the test as i am learning rust but not getting what to do according to your suggestion

**Comment by peterhuene** [comment]
Hi @Ankush1oo8. What you have there seems relatively correct, although I would probably restructure your `check_placeholder` to basically first check to see if there's an option:

If there is an option, follow the option's type requirements and emit a `invalid_placeholder_option` diagnostic if the expression type isn't what is expected.

If there is no option, only accept `Type::Primitive(..) | Type::Union | Type::None`, otherwise emit a `cannot_coerce_to_string` diagnostic.

Regarding testing, we can create a new `source.wdl` file under `wdl-analysis/tests/analysis/placeholders` that looks like this:

```wdl
# This is a test for analysis of placeholders and their options.
version 1.1

workflow test {
    String s1 = "~{true}" # OK
    String s2 = "~{true="yes" false="no" false}" # OK
    String s3 = "~{true="yes" false="no" 1}" # NOT OK
    # More test cases here...
}
```

If we run `cargo test -p wdl-analysis --all-features` with the `BLESS` environment variable set to `1`, it will generate a baseline file containing all of the expected diagnostics for the test case. We should then look the baseline over for correctness to ensure all of the diagnostics emitted for the test are what we expect.

**Comment by peterhuene** [comment]
@Ankush1oo8 Also, I merged in a refactoring which caused a conflict in `wdl-analysis/src/types/v1.rs`. If you need assistance with resolving the conflict, please let me know and I'm happy to help.

**Comment by Ankush1oo8** [comment]
@peterhuene can you check now

**Comment by Ankush1oo8** [comment]
@claymcleod yes doing that

**Comment by claymcleod** [comment]
@Ankush1oo8 looks like there are now some errors in the CI, if you could please address those.

File: wdl-analysis/src/types/v1.rs [hunk 5]
```diff
@@ -692,6 +693,33 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
 
+    fn invalid_placeholder_option(
+        ty: &Type,
+        _span: Span,
+        option: Option<PlaceholderOption>,
+    ) -> Diagnostic {
+        let message = match option {
+            Some(PlaceholderOption::Sep(_)) => format!(
+                "type mismatch for placeholder option `sep`: expected type `Array[P]` where P: any primitive type or Union, but found `{}`",
+                ty
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:704]: Nit: I generally prefer we put the expressions in the placeholder, makes the formatted string easier to read in source:

```suggestion
                "type mismatch for placeholder option `sep`: expected type `Array[P]` where P: any primitive type, but found `{ty}`"
```

We should also not have `Union` in any error messages; it's a hidden type and generally unknown to the users of WDL.

File: wdl-analysis/src/types/v1.rs [hunk 6]
```diff
@@ -692,6 +693,33 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
+            ),
+            Some(PlaceholderOption::Default(_)) => format!(
+                "type mismatch for placeholder option `default`: expected an optional primitive type, but found `{}`",
+                ty
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:708]:
```suggestion
                "type mismatch for placeholder option `default`: expected an optional primitive type, but found `{ty}`"
```

File: wdl-analysis/src/types/v1.rs [hunk 7]
```diff
@@ -692,6 +693,33 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
+            ),
+            Some(PlaceholderOption::TrueFalse(_)) => format!(
+                "type mismatch for placeholder option `truefalse`: expected type `Boolean`, but found `{}`",
+                ty
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:712]: For this one, we should probably use a `/` to delineate the placeholder name.
 
```suggestion
                "type mismatch for placeholder option `true/false`: expected type `Boolean`, but found `{ty}`"
```

File: wdl-analysis/src/types/v1.rs [hunk 8]
```diff
@@ -692,6 +693,33 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
+            ),
+            None => format!("cannot coerce type `{}` to `String`", ty),
+        };
+        Diagnostic::error(message) // No span here
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:716]: We should definitely be attaching a span to the error, otherwise it will default to the end of the file and that's not what we want.

```suggestion
        Diagnostic::error(message).with_label(format!("this is type `{ty}`"), span)
```

File: wdl-analysis/src/types/v1.rs [hunk 9]
```diff
@@ -692,6 +693,33 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
         self.placeholders -= 1;
     }
 
+    fn invalid_placeholder_option(
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:696]: We should move this function into `diagnostics.rs`, where we consolidate all diagnostic messages from static analysis.

File: wdl-analysis/src/types/v1.rs [hunk 10]
```diff
@@ -657,31 +657,32 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
-                                // OK
-                                coercible = true;
-                            }
-                        }
+            if let Some(option) = placeholder.option() {
+                let valid = match option {
+                    PlaceholderOption::Sep(_) => matches!(ty,
+                        Type::Compound(CompoundType::Array(ref element_type), false)
+                        if matches!(element_type.element_type(), Type::Primitive(_, false) | Type::Union)),
+                    PlaceholderOption::Default(_) => matches!(ty, Type::Primitive(_, true)),
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:669]: As `default` expects an optional primitive, we should also be accepting `Union` and `None` here.

```suggestion
                    PlaceholderOption::Default(_) => matches!(ty, Type::Primitive(_, true) | Type::Union | Type::None),
```

File: wdl-analysis/src/types/v1.rs [hunk 11]
```diff
@@ -657,31 +657,32 @@ impl<'a, C: EvaluationContext> ExprTypeEvaluator<'a, C> {
...
+                    PlaceholderOption::TrueFalse(_) => {
+                        matches!(ty, Type::Primitive(PrimitiveType::Boolean, _))
```
Comment (peterhuene) [inline wdl-analysis/src/types/v1.rs:671]: As `true/false` expects a non-optional `Boolean`, we should also be accepting only `Union` here.
 
```suggestion
                        matches!(ty, Type::Primitive(PrimitiveType::Boolean, false) | Type::Union)
```

File: wdl-analysis/tests/analysis/placeholder-options/source.diagnostics [hunk 12]
```diff
@@ -0,0 +1,6 @@
+error: type mismatch for placeholder option `sep`: expected type `Array[P]` where P: any primitive type or Union, but found `Boolean`
```
Comment (peterhuene) [inline wdl-analysis/tests/analysis/placeholder-options/source.diagnostics:1]: We'll need to regenerate the test baselines with `BLESS=1` with the above changes to `invalid_placeholder_option`.

File: wdl-analysis/tests/analysis/placeholders/source.wdl [hunk 13]
```diff
@@ -0,0 +1,13 @@
+# This is a test for analysis of placeholders and their options.
```
Comment (peterhuene) [inline wdl-analysis/tests/analysis/placeholders/source.wdl:1]: I think we should merge this with the `placeholder-options` test.

File: wdl-analysis/tests/analysis/type_checker_tests.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (peterhuene) [reply wdl-analysis/tests/analysis/type_checker_tests.rs:1]: Re-commenting here as I think we can delete this file.

**Review by peterhuene — COMMENTED** [review]
Hi @Ankush1oo8. We're getting close now!

Just a few comments relating to the diagnostic and the check.

**Comment by claymcleod** [comment]
@Ankush1oo8 still some CI checks that need to be addressed here.

**Comment by Ankush1oo8** [comment]
@peterhuene can you help me hat should I do

**Comment by a-frantz** [comment]
> @peterhuene can you help me hat should I do

@Ankush1oo8 
please read the contributing guide, where we have put instructions for this

https://github.com/stjude-rust-labs/wdl/blob/main/CONTRIBUTING.md#the-ci-has-turned-red-how-do-i-make-it-green-again

**Comment by Ankush1oo8** [comment]
@a-frantz can you check now I have made changes

**Review by peterhuene — APPROVED** [review]
Hi @Ankush1oo8.

I pushed up some final fixes to the tests and implemented a missing check in `wdl-engine`.

Once CI passes, we should be good to merge this.

Thanks again for all your hard work on fixing this!

**Comment by Ankush1oo8** [comment]
@peterhuene thank you
